#!/usr/bin/env python3
"""Post-sweep cleanup. Operates ONLY on a copy of the crawler DB.

Never opens the live crawler file for writing, never touches the crawler process.

Windows and Appliances use Ray's committed maps verbatim:
  market_context/clean_windows.py     -> ALIAS + EXCLUDE
  market_context/appliance_aliases.py -> APPLIANCE_ALIAS
Other categories get maps generated by spelling collapse, saved for review.
"""
import json, os, re, shutil, sys, collections, difflib, datetime, importlib.util, subprocess

LIVE  = "/home/ubuntu/spec-crawler/data/spec-crawler.json"
MAPS  = "/home/ubuntu/cleanup/maps"
OUT   = "/home/ubuntu/cleanup/out"
WORK  = "/home/ubuntu/cleanup/work"
SEARCH = "/home/ubuntu/spec-crawler/data/_listing_search.py"
args = sys.argv[1:]
def opt(f, d): return args[args.index(f) + 1] if f in args else d
LIVE = opt("--live", LIVE); OUT = opt("--out", OUT)
os.makedirs(OUT, exist_ok=True); os.makedirs(WORK, exist_ok=True)

R = []
def log(s=""): R.append(s); print(s, flush=True)

def load_py(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec)
    src = open(path, encoding="utf8").read()
    # keep only the literal map/set definitions; skip the script's file IO
    head = src.split("def norm(")[0]
    ns = {}
    exec(compile(head, path, "exec"), ns)
    return ns

TARGET_CATS = ["Doors", "Countertops", "Flooring", "Cabinets", "Smart Home",
               "HVAC", "Generators", "Water Treatment", "Plumbing", "Lighting"]

# Ray's Windows EXCLUDE list mixes three different things. Split it so window
# treatments get RECATEGORIZED (his cleanup plan) rather than dropped, and only
# genuine non-brands are dropped.
WT_RECAT = {
    'hunter douglas','hunter douglass','hunter-douglas','lutron','phantom',
    'phantom screens','motorized phantom','storm smart','storm smart screens',
    'silhouette','plantation','norman','carolina shutters','graber','shade store',
    'the shade store','levolor','luminette','polar shades','somfy','llumar','3m',
    'solarian','solar industries','enviroblind','sunburst','noseum','kevlar',
    'eze-breeze','ez breeze','eze breeze','shade co.',
}
SMART_RECAT = {'crestron'}
# not a brand, or unidentifiable from the token alone
JUNK_DROP = {'brown','quality','quartz','lifetime','smart','ez','es','mi','cws',
             'techno glass','solatube'}
THERMO_BRANDS = {'nest','google nest','ecobee','honeywell home'}
THERMO_WORDS = re.compile(r"\bthermostat|thermostats\b", re.I)

BANDS = [("under_1m", 0, 1_000_000), ("1_2m", 1_000_000, 2_000_000),
         ("2_3.5m", 2_000_000, 3_500_000), ("3.5_5m", 3_500_000, 5_000_000),
         ("5m_plus", 5_000_000, float("inf"))]
def money(s):
    if not s: return None
    d = re.sub(r"[^0-9]", "", str(s)); return int(d) if d else None
def band_of(p):
    if not p or p <= 100_000: return None
    for k, lo, hi in BANDS:
        if lo <= p < hi: return k
def norm_key(b):
    s = re.sub(r"&", " and ", (b or "").lower().strip())
    s = re.sub(r"[^a-z0-9]+", "", s)
    for suf in ("inc","llc","corp","corporation","company","co","appliances","appliance","usa"):
        if s.endswith(suf) and len(s) > len(suf) + 3: s = s[:-len(suf)]
    return s
# ---------------------------------------------------------------------------
# PERMANENT RULE (Ray, 2026-09-08): FREQUENCY NEVER PICKS THE CANONICAL NAME.
#
# Which spelling is correct is knowledge the crawler data does not contain. The
# crawler harvests listing copy, and listing copy misspells confidently: the data
# prefers "Carrera" over "Carrara" and "Consentino" over "Cosentino". Counting
# rows therefore gets the canonical name backwards often enough to corrupt the
# brand taxonomy, which is the asset.
#
# So: the canonical name comes from CANONICAL_AUTHORITY below. Frequency is the
# fallback ONLY when no group member matches the authority list, and any name
# chosen that way should be reviewed and promoted into the list. Do not replace
# this with a frequency heuristic, in this script or any successor.
# ---------------------------------------------------------------------------
CANONICAL_AUTHORITY = [
    "KitchenCraft", "California Closets", "Eggersmann", "Bellmont",
    "Taj Mahal", "Caesarstone", "Cristallo", "Pompeii", "Mont Blanc",
    "Carrara", "Cosentino", "Calacatta",
    "NanaWall", "Andersen", "Jeld-Wen", "Therma-Tru", "Cantera", "Milgard",
    "Windsor", "Masonite", "Pella",
    "DuChateau", "Provenza", "COREtec", "Pebble Tec", "Belgrade",
    "Generac", "Kohler", "Briggs & Stratton",
    "Daikin", "Reme Halo", "Infratech", "Buderus", "Lennox",
    "Bevolo", "Philips", "Arteriors", "Currey & Company", "Bowers & Wilkins",
    "Visual Comfort",
    "Dornbracht", "Kallista", "Phylrich", "Brizo", "Aquatica",
    "Crestron", "SimpliSafe", "Sonos", "B-Hyve",
    "Kinetico", "Aquasana",
    # Ray ruling 2026-09-08: kept distinct from each other, not variants.
    "Aquatic", "Aquatica", "Belmont", "Bellmont",
    # one edit from Windsor but a separate manufacturer
    "WinDoor",
]
AUTHORITY_BY_KEY = {}

# WinDoor Inc is a real manufacturer and sits one edit from Windsor. Keep it out
# of that group entirely rather than let the closure swallow it.
# Names locked as DISTINCT. The matcher must never join these to anything, even
# transitively. WinDoor Inc sits one edit from Windsor; the other four are Ray's
# Sept 8 ruling (Aquatic/Aquatica and Belmont/Bellmont are plausibly separate
# companies and the counts are too small to matter to any report).
NEVER_MERGE_KEYS = {"windoor", "aquatic", "aquatica", "belmont", "bellmont"}

# Passes the one-typo test but these are plausibly distinct firms, so per
# Ray's rule they stay flagged rather than merged.
NOT_SAME_COMPANY = set()   # settled cases now live in NEVER_MERGE_KEYS above

def edit_dist(a, b):
    """Levenshtein. Used to decide 'one obvious typo' per Ray's Sept 8 rule."""
    if a == b: return 0
    if abs(len(a) - len(b)) > 1: return 2
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1]

# Ray's Sept 8 rulings, applied by name regardless of what the rule computes.
RULED_MERGES = {
    ("cabinets", "californiacloset"): "California Closets",
    ("smart home", "iaqualink"): "Aqualink",
}

for _a in CANONICAL_AUTHORITY:
    AUTHORITY_BY_KEY[norm_key(_a)] = _a

JUNK = {"", "not specified", "notspecified", "n/a", "na", "none", "unknown",
        "other", "unspecified", "tbd", "various"}

now = datetime.datetime.now(datetime.timezone.utc)
log("# Post-sweep cleanup report")
log(f"Generated {now:%Y-%m-%d %H:%M} UTC")
log()

# ---------------------------------------------------------------- 0. sweep gate
state = json.load(open("/home/ubuntu/spec-crawler/data/national-scan-state.json"))
stale = [m for m, t in state["lastScanByMetro"].items() if t < "2026-09-08"]
log(f"Sweep gate: phase={state['phase']} metros_not_yet_reswept={len(stale)}")
if "--force" not in args and (state["phase"] != "refresh" or len(stale) > 0):
    log("SWEEP INCOMPLETE. Refusing to clean partial data.")
    log(f"  metros still stale: {', '.join(sorted(stale)[:40])}")
    open(os.path.join(OUT, "report.md"), "w").write("\n".join(R) + "\n")
    sys.exit(2)
log()

# ---------------------------------------------------------------- 1. copy
copy = os.path.join(WORK, "spec-crawler.copy.json")
shutil.copy2(LIVE, copy)
db = json.load(open(copy, encoding="utf8"))
n_list0, n_spec0 = len(db["listings"]), len(db["specs"])
log("## 1. Source")
log(f"  copied live DB read-only -> {copy}")
log(f"  {n_list0:,} listings, {n_spec0:,} specs, {len(db['builders']):,} builders")
log()

# ---------------------------------------------------------------- 2. dedupe
log("## 2. Deduplication")
seen_url, keep, remap = {}, [], {}
for l in db["listings"]:
    u = (l.get("url") or "").strip()
    if not u: keep.append(l); continue
    if u in seen_url: remap[l["id"]] = seen_url[u]["id"]
    else: seen_url[u] = l; keep.append(l)
db["listings"] = keep
log(f"  listings {n_list0:,} -> {len(keep):,}   ({n_list0-len(keep):,} duplicate rows removed)")
log(f"  {len(remap):,} listing ids repointed to the surviving row")
for b in db["builders"]:
    pass
seen_s, keep_s = set(), []
for s in db["specs"]:
    k = ((s.get("sourcePageUrl") or s.get("homeAddress") or "").strip().lower(),
         (s.get("productCategory") or "").strip().lower(),
         (s.get("brand") or "").strip().lower(),
         (s.get("modelSeries") or "").strip().lower())
    if k in seen_s: continue
    seen_s.add(k); keep_s.append(s)
db["specs"] = keep_s
log(f"  specs    {n_spec0:,} -> {len(keep_s):,}   ({n_spec0-len(keep_s):,} duplicate rows removed)")
log()

# ---------------------------------------------------------------- 3. brands
log("## 3. Brand normalization")
w = load_py(os.path.join(MAPS, "clean_windows.py"), "cw")
a = load_py(os.path.join(MAPS, "appliance_aliases.py"), "aa")
WIN_ALIAS, WIN_EXCLUDE = w["ALIAS"], w["EXCLUDE"]
APP_ALIAS = a["APPLIANCE_ALIAS"]
log(f"  clean_windows.py:     {len(WIN_ALIAS)} window aliases, {len(WIN_EXCLUDE)} exclusions")
log(f"  appliance_aliases.py: {len(APP_ALIAS)} appliance aliases")

percat = collections.defaultdict(collections.Counter)
for s in db["specs"]:
    b = (s.get("brand") or "").strip(); c = (s.get("productCategory") or "").strip()
    if b and b.lower() not in JUNK and c: percat[c][b] += 1
before_top = {c: collections.Counter(v) for c, v in percat.items()}

generated, flagged, auto_typo = {}, [], []
for cat, counter in percat.items():
    if cat.lower() in ("windows", "window", "appliances"): continue
    clusters = collections.defaultdict(list)
    for brand, n in counter.items(): clusters[norm_key(brand)].append((brand, n))
    for key, members in clusters.items():
        if len(members) < 2: continue
        members.sort(key=lambda x: -x[1])
        canon = members[0][0]
        al = [b for b, _ in members if b != canon]
        if al: generated[f"{canon}|{cat}"] = sorted(al)
    if cat in TARGET_CATS:
        keys = sorted(clusters, key=lambda k: -sum(n for _, n in clusters[k]))[:150]
        # union-find so chains (a~b, b~c) collapse to one canonical, not a chain
        parent = {k: k for k in keys}
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]; x = parent[x]
            return x
        def union(x, y):
            rx, ry = find(x), find(y)
            if rx != ry: parent[ry] = rx
        for i, x in enumerate(keys):
            for y in keys[i + 1:]:
                if not x or not y or abs(len(x) - len(y)) > 1: continue
                if x in NEVER_MERGE_KEYS or y in NEVER_MERGE_KEYS: continue
                if edit_dist(x, y) > 1: continue
                if min(len(x), len(y)) < 6: continue
                nx = sum(n for _, n in clusters[x]); ny = sum(n for _, n in clusters[y])
                bx = max(clusters[x], key=lambda t: t[1])[0]
                by = max(clusters[y], key=lambda t: t[1])[0]
                if frozenset((x, y)) in NOT_SAME_COMPANY:
                    big, small = (bx, by) if nx >= ny else (by, bx)
                    flagged.append({"category": cat, "canonical": big, "variant": small,
                                    "canonical_count": max(nx, ny), "variant_count": min(nx, ny),
                                    "reason": "one edit apart but plausibly two different companies"})
                    continue
                union(x, y)
        groups = collections.defaultdict(list)
        for k in keys: groups[find(k)].append(k)
        for root, members in groups.items():
            if len(members) < 2: continue
            spellings = [(b, n) for k in members for b, n in clusters[k]]
            # canonical: authority list first, else most frequent then fuller
            canon = None
            for k in members:
                if k in AUTHORITY_BY_KEY:
                    canon = AUTHORITY_BY_KEY[k]; break
            if canon is None:
                canon = sorted(spellings, key=lambda t: (-t[1], -len(t[0]), t[0]))[0][0]
            for b, n in spellings:
                if b == canon: continue
                generated.setdefault(f"{canon}|{cat}", [])
                if b not in generated[f"{canon}|{cat}"]:
                    generated[f"{canon}|{cat}"].append(b)
                auto_typo.append({"category": cat, "canonical": canon, "variant": b,
                                  "variant_count": n})
log(f"  generated {len(generated)} canonical groups for the other categories")
log(f"  merged {len(auto_typo)} variants under the one-typo rule (Ray, Sept 8): differ only by")
log("     spacing, punctuation, casing or a single character edit on a name of 6+ chars")
log(f"  flagged {len(flagged)} pairs left for your review, could be two different companies")
if auto_typo:
    log("  merged under the one-typo rule:")
    for m in sorted(auto_typo, key=lambda z: z.get("category", "")):
        src = m.get("source", "one-typo rule")
        log(f"     {m['category']:<18}{m['variant']} -> {m['canonical']}   [{src}]")
log(f"  locked as distinct names, never matched: {', '.join(sorted(NEVER_MERGE_KEYS))}")
log("  canonical names come from the authority list; frequency is fallback only")
if flagged:
    log("  left flagged:")
    for m in flagged:
        log(f"     {m['category']:<18}{m['variant']} ({m['variant_count']}) "
            f"vs {m['canonical']} ({m['canonical_count']})")

gen_lookup = {}
for (catl, nk), canon in RULED_MERGES.items():
    gen_lookup[(catl, nk)] = canon
    auto_typo.append({"category": catl, "canonical": canon, "variant": nk,
                      "source": "Ray ruling 2026-09-08"})
for combo, al in generated.items():
    canon, cat = combo.split("|", 1)
    gen_lookup[(cat.lower(), norm_key(canon))] = canon
    for x in al: gen_lookup[(cat.lower(), norm_key(x))] = canon

merged = collections.Counter(); dropped_junk = collections.Counter()
recat_wt = recat_sm = recat_th = 0
out_specs = []
for s in db["specs"]:
    b = (s.get("brand") or "").strip(); c = (s.get("productCategory") or "").strip()
    cl, bl = c.lower(), b.lower()
    if cl in ("windows", "window"):
        if bl in WT_RECAT:
            s["productCategory"] = "Window Treatments"; recat_wt += 1; out_specs.append(s); continue
        if bl in SMART_RECAT:
            s["productCategory"] = "Smart Home"; recat_sm += 1; out_specs.append(s); continue
        if bl in JUNK_DROP:
            dropped_junk[b] += 1; continue
        nb = WIN_ALIAS.get(bl, b)
        if nb != b: s["brand"] = nb; merged["Windows"] += 1
    elif cl == "appliances":
        nb = APP_ALIAS.get(bl, b)
        if nb != b: s["brand"] = nb; merged["Appliances"] += 1
    else:
        if cl == "hvac":
            blob = " ".join(str(s.get(k) or "") for k in ("modelSeries", "fullDescription"))
            if bl in THERMO_BRANDS or THERMO_WORDS.search(blob):
                s["productCategory"] = "Smart Home"; recat_th += 1; out_specs.append(s); continue
        nb = gen_lookup.get((cl, norm_key(b)))
        if nb and nb != b: s["brand"] = nb; merged[c] += 1
    out_specs.append(s)
db["specs"] = out_specs
log("  rows rewritten by category:")
for c, n in merged.most_common(): log(f"     {c:<24}{n:>9,}")
log()
log("## 4. Recategorization")
log(f"  Windows -> Window Treatments : {recat_wt:,} rows")
log(f"  Windows -> Smart Home        : {recat_sm:,} rows")
log(f"  HVAC    -> Smart Home        : {recat_th:,} rows (thermostats)")
log(f"  Windows dropped as non-brand : {sum(dropped_junk.values()):,} rows "
    f"({', '.join(f'{k} {v}' for k, v in dropped_junk.most_common(8))})")
log()

# ---------------------------------------------------- 5. indexes, per home
log("## 5. Index regeneration, one count per home")
homes = {}
for s in db["specs"]:
    h = (s.get("sourcePageUrl") or s.get("homeAddress") or "").strip().lower()
    if not h: continue
    e = homes.setdefault(h, {"price": None, "state": "", "pairs": set()})
    if e["price"] is None: e["price"] = money(s.get("homePrice"))
    if not e["state"]: e["state"] = (s.get("homeState") or "").strip()
    b = (s.get("brand") or "").strip(); c = (s.get("productCategory") or "").strip()
    if b and b.lower() not in JUNK and c: e["pairs"].add((b, c))
homes_with = {h: v for h, v in homes.items() if v["pairs"]}
log(f"  distinct homes: {len(homes):,}   with named specs: {len(homes_with):,}")

brands = {}
for h, e in homes_with.items():
    bd = band_of(e["price"]); st = e["state"]
    for b, c in e["pairs"]:
        x = brands.setdefault(f"{b}|{c}", {"bands": {k: 0 for k, _, _ in BANDS}, "states": {}})
        x["bands"]["total"] = x["bands"].get("total", 0) + 1
        if bd: x["bands"][bd] += 1
        if st: x["states"][st] = x["states"].get(st, 0) + 1
mci = {"generated": now.strftime("%Y-%m-%d"), "cleaned": True,
       "counting": "one count per home",
       "source_listings": len(db["listings"]), "source_specs": len(db["specs"]),
       "source_homes": len(homes_with), "brands": brands}
json.dump(mci, open(os.path.join(OUT, "market-context-index.json"), "w"), indent=1)
log(f"  market-context-index.json: {len(brands):,} brand x category combos")

base = collections.Counter()
for h, e in homes_with.items():
    for b, c in e["pairs"]: base[f"{c}|{b}"] += 1
pairs = collections.Counter()
for h, e in homes_with.items():
    keys = sorted(f"{c}|{b}" for b, c in e["pairs"])
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            pairs[f"{keys[i]} && {keys[j]}"] += 1
MINP, MINB = 20, 15
cooc = {"generated": now.strftime("%Y-%m-%d"), "cleaned": True,
        "counting": "one count per home",
        "listings_with_specs": len(homes_with), "min_pair_count": MINP,
        "brand_listing_counts": {k: v for k, v in sorted(base.items(), key=lambda x: -x[1]) if v >= MINB},
        "pairs": {k: v for k, v in sorted(pairs.items(), key=lambda x: -x[1]) if v >= MINP}}
json.dump(cooc, open(os.path.join(OUT, "co-occurrence-index.json"), "w"), indent=1)
log(f"  co-occurrence-index.json: {len(cooc['pairs']):,} pairs at >={MINP} homes, "
    f"{len(cooc['brand_listing_counts']):,} brands at >={MINB}")
log()

json.dump(generated, open(os.path.join(OUT, "brand-alias-map.generated.json"), "w"), indent=1, sort_keys=True)
json.dump({"auto_merged_typos": auto_typo, "needs_ruling": flagged,
           "windows_dropped_non_brand": dict(dropped_junk)},
          open(os.path.join(OUT, "flagged-for-review.json"), "w"), indent=1)

# ---------------------------------------------------- 6. Texas verification
log("## 6. Texas sweep verification")
for loc in ["Houston, TX", "Dallas, TX", "Austin, TX"]:
    q = json.dumps({"location": loc, "priceMin": 750000, "yearBuiltMin": 2000,
                    "listingType": "sold", "limit": 2000,
                    "dateFrom": "2026-03-09", "dateTo": now.strftime("%Y-%m-%d")})
    try:
        r = subprocess.run(["python3", SEARCH, q], capture_output=True, text=True, timeout=300)
        d = json.loads(r.stdout); rows = d if isinstance(d, list) else d.get("listings", [])
        hist = collections.Counter((x.get("soldDate") or "?")[:7] for x in rows)
        log(f"\n  {loc}: {len(rows):,} sold in the six-month window")
        for m in sorted(hist): log(f"     {m}: {hist[m]:>4} {'#'*min(40, hist[m]//5)}")
        miss = [m for m in ("2026-04","2026-05","2026-06","2026-07") if m not in hist]
        log(f"     Apr-Jul: {'ALL FOUR PRESENT' if not miss else 'MISSING ' + ','.join(miss)}")
    except Exception as e:
        log(f"  {loc}: verification query failed: {e}")
log()

# ---------------------------------------------------- 7. top ten
log("## 7. Top ten before and after")
for cat in ("Appliances", "Windows"):
    after = collections.Counter()
    for h, e in homes_with.items():
        for b, c in e["pairs"]:
            if c == cat: after[b] += 1
    bef = before_top.get(cat, collections.Counter())
    log(f"\n### {cat}")
    log(f"  {'brand':<28}{'before rows':>13}{'after homes':>13}")
    for b, n in after.most_common(10):
        log(f"  {b:<28}{bef.get(b,0):>13,}{n:>13,}")
    log(f"  before, raw top ten: " + ", ".join(f"{b} ({n:,})" for b, n in bef.most_common(10)))
log()
log(f"## Totals")
log(f"  listings {n_list0:,} -> {len(db['listings']):,}")
log(f"  specs    {n_spec0:,} -> {len(db['specs']):,}")
log(f"  homes with named specs: {len(homes_with):,}")

json.dump(db, open(os.path.join(WORK, "spec-crawler.cleaned.json"), "w"))
open(os.path.join(OUT, "report.md"), "w").write("\n".join(R) + "\n")
print("\nWROTE", OUT)
